<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SignUP_TS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d5119de5-fc12-4e92-b568-47f56d1a3e30</testSuiteGuid>
   <testCaseLink>
      <guid>d2ff0023-9788-4629-ad46-1c1dd6591700</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>db662b24-d4af-4702-84ec-1209fd47bacd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loginlist</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>db662b24-d4af-4702-84ec-1209fd47bacd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fullname</value>
         <variableId>bb5552af-45c8-4969-80e2-80392bf496e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>db662b24-d4af-4702-84ec-1209fd47bacd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>e33bad48-db43-4ebc-a3f9-db3b90b09900</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>db662b24-d4af-4702-84ec-1209fd47bacd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6a22b1e1-6188-41cc-a9b3-33ece12f5201</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>db662b24-d4af-4702-84ec-1209fd47bacd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cpassword</value>
         <variableId>95b8bb2a-5fea-4b65-9acc-8b496fbd7a87</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
